### ISSUE TITLE
Emoji favicon

### ISSUE THREAD

**Issue by SimonMarquis** [wincelau/ratpstatus#5]
Bonjour @wincelau, quel est ton avis sur l'ajout de favicon dynamique ?
Actuellement il n'y a aucune favicon, et l'icone par défaut apparait.
Avoir l'emoticon directement en tant que favicon (au lieu du titre) serait plus pratique, et permettrait de distinguer les pages dans mes bookmarks :)
Cette contribution serait acceptée ?

![image](https://github.com/wincelau/ratpstatus/assets/1921278/095f6e9e-07a6-4a2f-a4df-867100163a6d)

**Comment by wincelau** [comment]
Bonjour,

J'ai fait un favicon identique pour toutes les pages : 
![favicon](https://github.com/wincelau/ratpstatus/assets/6379869/ba984eaa-62b4-4f9a-be46-87a850a49b7a)

Je veux bien votre avis ?

**Comment by wincelau** [comment]
Oui bien celui-ci : https://github.com/wincelau/ratpstatus/blob/main/images/favicon2.png ?

**Comment by wincelau** [comment]
Oui celui-ci

![favicon3](https://github.com/wincelau/ratpstatus/assets/6379869/fd3154de-b345-43c0-9e72-65f2a406849d)

**Comment by wincelau** [comment]
![favicon_originale_2](https://github.com/wincelau/ratpstatus/assets/6379869/d084e9c9-a9bb-41bc-8074-8411997cf7a1)

**Comment by wincelau** [comment]
![favicon](https://github.com/wincelau/ratpstatus/assets/6379869/07bc06a4-1aa0-413f-961d-0b61f72aefb8)

**Comment by wincelau** [comment]
Ou bien votre idée de base avec un favicon différent pour chaque page ?

**Comment by wincelau** [comment]
![Uploading favicon_originale_4.png…]()

**Comment by wincelau** [comment]
![favicon_originale_4](https://github.com/wincelau/ratpstatus/assets/6379869/21a286ed-9004-4701-a7cd-cde7dce65eae)

**Comment by wincelau** [comment]
J'ai tenté de trouver un logo générique pour le favicon, et rien de concluant pour le moment.

J'ai fait ce que tu m'as suggérée et j'aime bien l'idéé : https://github.com/wincelau/ratpstatus/commit/4981703af61ca7752aa4f388346db5641f5bc9d5

Il manquera encore peut être  une personnalisation du favicon pour avoir le côté "status", mais pour le moment je vois pas quoi faire.
